# Generated by Django 6.0.1 on 2026-03-01 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='method_of_payment',
        ),
        migrations.RemoveField(
            model_name='mpesarequest',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='mpesaresponse',
            name='request',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.DeleteModel(
            name='MethodPay',
        ),
        migrations.DeleteModel(
            name='MpesaRequest',
        ),
        migrations.DeleteModel(
            name='MpesaResponse',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
