# Generated by Django 6.0.1 on 2026-04-18 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_companyinvitation_company_slug'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesarequest',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
    ]
