# Generated by Django 6.0.1 on 2026-04-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_mpesarequest_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='payment_type',
            field=models.CharField(choices=[('deposit', 'Deposit (70%)'), ('balance', 'Balance (30%)'), ('full', 'Full Payment')], max_length=20),
        ),
    ]
