# Generated by Django 6.0.1 on 2026-03-01 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LegalDocument',
        ),
    ]
