# Generated by Django 6.0.1 on 2026-02-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(choices=[('wedding_card', 'Wedding Card'), ('book', 'Book'), ('plate', 'Plate'), ('hoodie', 'Hoodie'), ('nocat', 'No Category'), ('calendar', 'Calendar')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('color_mode', models.CharField(choices=[('bw', 'Black & White'), ('color', 'Full Color')], default='color', max_length=20)),
                ('paper_type', models.CharField(blank=True, max_length=100, null=True)),
                ('paper_size', models.CharField(blank=True, max_length=50, null=True)),
                ('number_of_pages', models.PositiveIntegerField(blank=True, null=True)),
                ('has_spine', models.BooleanField(default=False)),
                ('spine_size_mm', models.FloatField(blank=True, null=True)),
                ('binding_type', models.CharField(blank=True, choices=[('perfect', 'Perfect Binding'), ('spiral', 'Spiral Binding'), ('hardcover', 'Hardcover'), ('stapled', 'Stapled')], max_length=50, null=True)),
                ('size', models.CharField(blank=True, max_length=20, null=True)),
                ('material', models.CharField(blank=True, max_length=100, null=True)),
                ('plate_diameter_cm', models.FloatField(blank=True, null=True)),
                ('design_file', models.FileField(blank=True, null=True, upload_to='designs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
