# Generated by Django 6.0.1 on 2026-02-11 09:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(default=1, help_text='upload an image', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
