# Generated by Django 6.0.1 on 2026-02-26 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_banner_book_card_clothes_envelope_flyer_pen_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('card', 'Card'), ('banner', 'Banner'), ('clothes', 'Clothes'), ('book', 'Book'), ('flyer', 'Flyer'), ('pen', 'Pen'), ('envelope', 'Envelope')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('quantity', models.PositiveIntegerField()),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('material', models.CharField(blank=True, max_length=100, null=True)),
                ('cover_type', models.CharField(blank=True, max_length=50, null=True)),
                ('lamination', models.CharField(blank=True, max_length=50, null=True)),
                ('binding', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('pen_type', models.CharField(blank=True, max_length=50, null=True)),
                ('design_file', models.ImageField(blank=True, null=True, upload_to='designs/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('printing', 'Printing'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='Clothes',
        ),
        migrations.DeleteModel(
            name='Envelope',
        ),
        migrations.DeleteModel(
            name='Flyer',
        ),
        migrations.RemoveField(
            model_name='item_order',
            name='user',
        ),
        migrations.DeleteModel(
            name='Pen',
        ),
        migrations.DeleteModel(
            name='Item_order',
        ),
    ]
