# Generated by Django 6.0.1 on 2026-03-01 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_itemorder_delete_banner_delete_book_delete_card_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
