# Generated by Django 6.0.1 on 2026-03-04 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='base_price',
            new_name='price',
        ),
    ]
