# Generated by Django 6.0.1 on 2026-04-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinvitation',
            name='company',
        ),
        migrations.AddField(
            model_name='companyinvitation',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
