# Generated by Django 6.0.1 on 2026-04-09 09:04

import companies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_remove_companyinvitation_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinvitation',
            name='token',
            field=models.CharField(default=companies.models.CompanyInvitation.generate_token, editable=False, max_length=64, unique=True),
        ),
    ]
