# Generated by Django 6.0.1 on 2026-03-07 13:01

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('needs_design', models.BooleanField(default=False)),
                ('design_file', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='design')),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending_design', 'Pending Design'), ('design_completed', 'Design Completed'), ('design_rejected', 'Rejected By Designer'), ('approved', 'Approved For Printing'), ('printing', 'Printing'), ('completed', 'Completed')], default='pending_design', max_length=30)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='myapp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
