# Generated by Django 6.0.1 on 2026-02-19 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_pages', models.IntegerField(blank=True, null=True)),
                ('binding_type', models.CharField(blank=True, max_length=50, null=True)),
                ('has_spine', models.BooleanField(default=False)),
                ('spine_size_mm', models.FloatField(blank=True, null=True)),
                ('size', models.CharField(blank=True, max_length=20, null=True)),
                ('material', models.CharField(blank=True, max_length=100, null=True)),
                ('plate_diameter_cm', models.FloatField(blank=True, null=True)),
                ('paper_type', models.CharField(blank=True, max_length=50, null=True)),
                ('cover_type', models.CharField(blank=True, max_length=50, null=True)),
                ('paper_size', models.CharField(blank=True, max_length=50, null=True)),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.orderitem')),
            ],
        ),
    ]
