# Generated by Django 6.0.1 on 2026-02-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('in_design', 'In Design'), ('on_printing', 'On Printing'), ('on_delivery', 'On Delivery'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
