# Generated by Django 6.0.1 on 2026-02-24 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderitem_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItemSpecification',
        ),
    ]
