# Generated by Django 6.0.1 on 2026-02-24 22:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_delete_orderitemspecification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCreateForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('color_type', models.CharField(blank=True, max_length=50)),
                ('design_type', models.CharField(blank=True, choices=[('designed', 'I have my design'), ('not_designed', 'I want it designed')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('number_of_pages', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('binding_type', models.CharField(blank=True, choices=[('perfect', 'Perfect Binding'), ('spiral', 'Spiral Binding'), ('hardcover', 'Hardcover'), ('stapled', 'Stapled')], max_length=20)),
                ('has_spine', models.BooleanField(blank=True)),
                ('spine_size_mm', models.FloatField(blank=True)),
                ('paper_type', models.CharField(blank=True, choices=[('matte', 'Matte'), ('glossy', 'Glossy'), ('book_paper', 'Book Paper')], max_length=20)),
                ('cover_type', models.CharField(blank=True, choices=[('matte', 'Matte'), ('glossy', 'Glossy')], max_length=20)),
                ('paper_size', models.CharField(blank=True, max_length=50)),
                ('size', models.CharField(blank=True, max_length=20)),
                ('material', models.CharField(blank=True, max_length=100)),
                ('plate_diameter_cm', models.FloatField(blank=True)),
                ('design_file', models.FileField(blank=True, upload_to='designes/')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
