# Generated by Django 6.0.1 on 2026-02-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_rejection_reason_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='color_type',
            field=models.CharField(choices=[('full_color', 'Full Color'), ('black_white', 'Black & White')], default='full_color', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='design_type',
            field=models.CharField(choices=[('designed', 'Already Designed'), ('not_designed', 'Not Designed')], default='not_designed', max_length=20),
        ),
    ]
