# Generated by Django 6.0.1 on 2026-02-14 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_color_type_order_design_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_mode',
            field=models.CharField(blank=True, choices=[('uber', 'Uber Delivery'), ('pickup', 'Client Pickup')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('on_delivery', 'On Delivery'), ('arrived', 'Arrived Safely'), ('issue', 'Delivery Issue')], default='waiting', max_length=20),
        ),
        migrations.CreateModel(
            name='DesignDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('paper_type', models.CharField(choices=[('glossy', 'Glossy'), ('matte', 'Matte'), ('bond', 'Bond Paper')], max_length=20)),
                ('editing_type', models.CharField(choices=[('basic', 'Basic Editing'), ('advanced', 'Advanced Editing')], max_length=20)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
    ]
