# Generated by Django 6.0.1 on 2026-03-01 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_delete_message'),
        ('deliveries', '0002_remove_deliveryissue_delivery_and_more'),
        ('designs', '0002_remove_designrequest_designer_and_more'),
        ('documents', '0002_delete_legaldocument'),
        ('orders', '0005_ordercreateform'),
        ('payments', '0002_remove_payment_method_of_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='client',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='ordercreateform',
            name='client',
        ),
        migrations.DeleteModel(
            name='DesignDetail',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='OrderCreateForm',
        ),
    ]
