# Generated by Django 6.0.1 on 2026-03-01 22:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='design_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='design'),
        ),
    ]
