# Generated by Django 6.0.1 on 2026-03-01 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_design_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='wants_design',
            new_name='needs_design',
        ),
    ]
