# Generated by Django 6.0.1 on 2026-03-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_rename_wants_design_order_needs_design'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned To Designer'), ('design_rejected', 'Rejected By Designer'), ('design_completed', 'Design Completed'), ('print_rejected', 'Rejected By Printer'), ('approved', 'Approved For Printing'), ('in_print', 'In Print'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
