# Generated by Django 6.0.1 on 2026-03-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_remove_order_assigned_designer_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_design', 'Pending Design'), ('design_completed', 'Design Completed'), ('design_rejected', 'Rejected By Designer'), ('approved', 'Approved For Printing'), ('in_print', 'In Print'), ('print_rejected', 'Rejected By Printer'), ('completed', 'Completed')], default='pending_design', max_length=30),
        ),
    ]
