# Generated by Django 6.0.1 on 2026-03-01 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryissue',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='deliveryissue',
            name='reported_by',
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
        migrations.DeleteModel(
            name='DeliveryIssue',
        ),
    ]
