# Generated by Django 6.0.1 on 2026-03-25 19:38

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='companies.company')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('gallery', models.JSONField(blank=True, default=list)),
                ('min_quantity', models.PositiveIntegerField(default=1)),
                ('max_quantity', models.PositiveIntegerField(default=10000)),
                ('requires_design', models.BooleanField(default=False)),
                ('design_templates', models.JSONField(blank=True, default=list)),
                ('print_specs', models.JSONField(blank=True, default=dict)),
                ('has_quantity_pricing', models.BooleanField(default=False)),
                ('quantity_pricing', models.JSONField(blank=True, default=list)),
                ('production_time', models.PositiveIntegerField(default=24, help_text='Hours')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='companies.company')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('email', 'Email'), ('phone', 'Phone'), ('textarea', 'Text Area'), ('select', 'Select'), ('checkbox', 'Checkbox'), ('file', 'File Upload'), ('date', 'Date')], max_length=20)),
                ('required', models.BooleanField(default=True)),
                ('options', models.JSONField(blank=True, default=list)),
                ('placeholder', models.CharField(blank=True, max_length=200)),
                ('help_text', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_fields', to='companies.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='products.product')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['company'], name='products_ca_company_3dcde4_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['company', 'is_active'], name='products_ca_company_453b1d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('company', 'slug')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['company'], name='products_pr_company_71d1d5_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['company', 'is_active'], name='products_pr_company_088709_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='products_pr_categor_9edb3d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('company', 'slug')},
        ),
        migrations.AddIndex(
            model_name='productfield',
            index=models.Index(fields=['company'], name='productfield_company_idx'),
        ),
    ]
