# Generated by Django 6.0.1 on 2026-03-25 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='product_company_idx',
            old_name='products_pr_company_71d1d5_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='product_company_active_idx',
            old_name='products_pr_company_088709_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='product_category_idx',
            old_name='products_pr_categor_9edb3d_idx',
        ),
    ]
